# .fo.yaml

# Global settings for fo behavior (can be overridden by CLI flags)
stream: false
show_output: "on-fail" # on-fail, always, never
max_buffer_size: 10485760 # 10MB
max_line_length: 1048576 # 1MB
no_timer: false
no_color: false # If true, would force a monochrome theme or behavior
ci: false # If true, might force a specific CI-friendly theme
debug: false

# Active theme - can be overridden by --theme flag or FO_THEME env var
active_theme: "unicode_vibrant"

# Presets for specific commands (your existing structure)
presets:
  go:
    label: "Go Build"
  golangci-lint:
    label: "Linting"
  # ... etc.

# --- THEMES DEFINITIONS ---
themes:
  # Theme 1: Pure ASCII, monochrome, line-oriented
  ascii_minimal:
    # General style properties for this theme
    style_properties: # Corresponds to design.Config.Style
      UseBoxes: false # CRITICAL for line-oriented
      Indentation: "  "
      ShowTimestamps: false # Overall start/end fo timestamps
      ReduceContrast: false
      Density: "compact"
      NoTimer: false # For individual task timers

    # Icons (ASCII fallbacks)
    icons: # Corresponds to design.Config.Icons
      Start: "[>]"
      Success: "[OK]"
      Warning: "[WW]" # Differentiated for status lines
      Error: "[!!]"
      Info: "[ii]"
      # Specific prefixes for output lines will be part of the element style
      # For example, Stderr_Error_Line_Prefix below

    # Colors (all empty or reset codes for monochrome)
    colors: # Corresponds to design.Config.Colors
      Process: "" # No color
      Success: ""
      Warning: ""
      Error: ""
      Detail: ""
      Muted: ""
      Reset: "" # Should be empty if no colors used

    # Border characters (mostly for tables in this theme)
    border: # Corresponds to design.Config.Border
      Style: "none" # This refers to task container style
      # For tables (which ARE boxed in this theme):
      Table_HChar: "-"
      Table_VChar: "|"
      Table_XChar: "+" # Intersection

    # --- Styleable Elements (using our agreed list as keys) ---
    elements:
      Fo_Banner_Top: { line_char_top: "=", line_char_bottom: "=", prefix_text: "FO:", text_style: ["bold"] }
      Fo_Timestamp_Start: { prefix_text: "FO: STARTED AT ", date_time_format: "2006-01-02 15:04:05" }
      # ... other Fo_Banner_Bottom elements ...
      Fo_OverallStatus_Success: { text_content: "SUCCESS", text_style: ["bold"] } # Icon comes from theme.icons.Success
      Fo_OverallStatus_Failed: { text_content: "FAILED", text_style: ["bold"] }
      Fo_OverallStatus_Warnings: { text_content: "WARNINGS", text_style: ["bold"] }

      H2_Target_Header_Line: { line_char: "-", line_length_type: "full_width" }
      H2_Target_Title: { prefix_text: "TARGET: ", text_case: "upper", text_style: ["bold"] }
      H2_Target_Footer_Line:
        {
          framing_char_start: "---- ",
          framing_char_end: " ----",
          inner_text_format: "{target_name}: {status_marker} {status_text} (Duration: {duration})",
        }

      Command_Line_Prefix: { text: "  -> CMD:", text_style: [] }
      Stdout_Line_Prefix: { text: "    | " } # Includes indent and symbol
      Stderr_Warning_Line_Prefix: { text: "    ! WARN: " }
      Stderr_Error_Line_Prefix: { text: "    X ERROR: " }
      Make_Info_Line_Prefix: { text: "INFO: " }

      Status_Label_Prefix: { text: "  STAT:", text_style: [] }
      Task_Status_Success_Block: { text_content: "PASSED" } # Icon from theme.icons.Success
      Task_Status_Failed_Block: { text_content: "FAILED" } # Icon from theme.icons.Error
      Task_Status_Warning_Block: { text_content: "WARNINGS" } # Icon from theme.icons.Warning
      Task_Status_Duration: { prefix_char: "(", suffix_char: ")", time_format: "default" }

      # Table styles for summary
      Table_Border_Horizontal: { char: "-" }
      Table_Border_Vertical: { char: "|" }
      Table_Border_Intersection_Cross: { char: "+" }
      Table_Header_Cell_Text: { text_style: ["bold"] }

  # Theme 2: Richer, Unicode symbols, colors, boxed tasks
  unicode_vibrant:
    # General style properties for this theme
    style_properties: # Corresponds to design.Config.Style
      UseBoxes: true # CRITICAL for boxed tasks
      Indentation: "  "
      ShowTimestamps: false
      ReduceContrast: false
      Density: "balanced"
      NoTimer: false

    # Icons (Unicode/Emoji)
    icons: # Corresponds to design.Config.Icons
      Start: "▶️"
      Success: "✅"
      Warning: "⚠️"
      Error: "❌"
      Info: "ℹ️"

    # Colors (ANSI codes)
    colors: # Corresponds to design.Config.Colors
      Process: "\033[0;34m" # Blue
      Success: "\033[0;32m" # Green
      Warning: "\033[0;33m" # Yellow
      Error: "\033[0;31m" # Red
      Detail: "\033[0m" # Default terminal color
      Muted: "\033[2m" # Dim
      Reset: "\033[0m"

    # Border characters (for Task_Container style "left_double" or similar)
    border: # Corresponds to design.Config.Border
      Style: "left_double" # This is one of your existing enums
      HeaderChar: "═"
      VerticalChar: "│"
      TopCornerChar: "╒"
      BottomCornerChar: "└"
      # Table chars can be same or different
      Table_HChar: "─"
      Table_VChar: "│"
      Table_XChar: "┼"

    # --- Styleable Elements ---
    elements:
      Fo_Banner_Top:
        { line_char_top: "═", line_char_bottom: "═", prefix_text: "FO:", text_style: ["bold"], color_fg: "blue" }
      Fo_Timestamp_Start: { prefix_text: "FO: STARTED AT ", date_time_format: "2006-01-02 15:04:05", color_fg: "blue" }
      # ... other Fo_Banner_Bottom elements ...
      Fo_OverallStatus_Success: { text_content: "SUCCESS", text_style: ["bold"] } # Icon and color from theme.icons/colors
      Fo_OverallStatus_Failed: { text_content: "FAILED", text_style: ["bold"] }
      Fo_OverallStatus_Warnings: { text_content: "WARNINGS", text_style: ["bold"] }

      # Task_Container uses border settings from theme.border above
      Task_Label_Header:
        {
          text_case: "upper",
          text_style: ["bold"],
          color_fg_label: "default",
          color_fg_border: "default",
          header_line_fill_char: "═",
        }
      Task_StartIndicator_Line: { text_style_label: [], color_fg_label: "blue" } # Icon and color from theme.icons/colors

      # For boxed themes, prefixes for content lines are often just the indentation
      # after the box's vertical char, which is handled by render.go logic
      Stdout_Line_Prefix: { additional_chars: "  " }
      Stderr_Warning_Line_Prefix: { additional_chars: "  " } # Icon and color come from styling the text itself
      Stderr_Error_Line_Prefix: { additional_chars: "  " }
      Make_Info_Line_Prefix: { text: "INFO: ", color_fg: "blue" } # If shown outside a task box

      # Actual text styling for these lines
      Task_Content_Stderr_Warning_Text: { text_style: [] } # Color from theme.colors.Warning, Icon from theme.icons.Warning
      Task_Content_Stderr_Error_Text: { text_style: [] } # Color from theme.colors.Error, Icon from theme.icons.Error (render.go applies italics for LoadHigh)

      Status_Label_Prefix: { text: "" } # No explicit "STAT:" needed if status is part of box
      Task_Status_Success_Block: { text_content: "Complete" }
      Task_Status_Failed_Block: { text_content: "Failed" }
      Task_Status_Warning_Block: { text_content: "Completed with warnings" }
      Task_Status_Duration: { prefix_char: "(", suffix_char: ")", time_format: "default", color_fg: "muted" }
      Task_Footer_Border_Continuation: { char: "─" } # For styles like left_double's "└─"

      # Table styles for summary
      Table_Border_Horizontal: { char: "─" }
      Table_Border_Vertical: { char: "│" }
      Table_Border_Intersection_Cross: { char: "┼" }
      Table_Header_Cell_Text: { text_style: ["bold"], color_fg: "blue" }
      Table_Body_Cell_Text: { color_fg: "default" }
