run:
  timeout: 5m
  go: '1.22'

linters:
  disable:
    # Overly strict style linters
    - wsl        # whitespace style is too opinionated
    - paralleltest  # requires careful analysis of each test
    - tagliatelle   # snake_case is standard for yaml configs

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: false
  goconst:
    min-occurrences: 4
  gosec:
    excludes:
      - G306
  # Set reasonable complexity thresholds for this codebase
  gocognit:
    min-complexity: 85
  cyclop:
    max-complexity: 50
  gocyclo:
    min-complexity: 50
  funlen:
    lines: 170
    statements: 100
  lll:
    line-length: 140
  nestif:
    min-complexity: 35
  maintidx:
    under: 15

issues:
  exclude-rules:
    # Allow os.Chdir in tests (usetesting linter)
    - path: _test\.go
      linters:
        - usetesting
    # Allow test packages to use same package name
    - path: _test\.go
      linters:
        - testpackage
    # Allow gosec G306 in tests
    - path: _test\.go
      linters:
        - gosec
    # Exclude dupword for comments
    - linters:
        - dupword
      source: "^\\s*//"
    # Allow fmt.Print* in magetasks - build tools need console output
    - path: internal/magetasks/
      linters:
        - forbidigo
